name: Django CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./testproject   # 👈 this is key

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django pytest pytest-django
          # pip install -r requirements.txt  # Uncomment if you have this

      - name: Run Django checks
        run: python manage.py check

      - name: Run tests
        run: python manage.py test
